---
driver:
  name: docker

platforms:
- name: ubuntu-12.04
  driver_config:
    image: ubuntu:12.04
    platform: ubuntu
  run_list:
  - recipe[mysql]

suites:
  - name: default
    run_list:
      - recipe[mysql]
    attributes: