---
driver:
  name: docker

platforms:
- name: centos-6.5
  driver_config:
    image: centos
    platform: rhel
  run_list:
  - recipe[mysql]

suites:
  - name: default
    run_list:
      - recipe[mysql]
    attributes: